/**
 * CERTIFICATE SIGNING — the shared vocabulary.
 *
 * One module names the document kinds, the panels who sign them, and — the part
 * that matters most — WHERE the signature blocks sit on the page.
 *
 * WHY THE LAYOUT LIVES HERE
 * -------------------------
 * Two things have to agree about the position of every signature block: the
 * generator that draws the ruled line on the PDF, and the field placement that
 * tells SignNow where to put the signing box. If they disagree by 20 points the
 * signature lands next to the line instead of on it, and nobody notices until a
 * member is holding the paper. So neither of them owns the numbers — this does,
 * and both read from it.
 *
 * COORDINATES
 * -----------
 * PDF points, from the TOP-LEFT of the page. jsPDF (constructed with unit:'pt')
 * and SignNow both use that origin, so a number here is used unchanged by both.
 * pdf-lib does NOT — it measures from the bottom-left — so anything that later
 * stamps these positions with pdf-lib must flip y. See applySignatureToPDF.js,
 * which is a separate path and does its own thing.
 */

/** Certificate kinds that can be routed through a signature before issuance. */
export const DOC_KINDS = {
  share_certificate: {
    label: 'Share certificate',
    sourceTable: 'sacco_share_certificates',
    blurb: 'Issued to a member for their holding, and shown to banks as proof of it.',
  },
  settlement_certificate: {
    label: 'Settlement & ownership transfer',
    sourceTable: 'installment_plans',
    blurb: 'Confirms a plan is paid off and ownership has passed. Often the buyer’s only proof.',
  },
  asset_valuation: {
    label: 'Asset valuation certificate',
    sourceTable: 'sacco_fixed_assets',
    blurb: 'States what an asset on the register is worth, and who stands behind that figure.',
  },
  guarantee_agreement: {
    label: 'Loan guarantee agreement',
    sourceTable: 'sacco_loan_guarantees',
    blurb: 'The undertaking a member signs to stand behind another member’s loan, and the only thing the society can produce when it comes to recover.',
    // Welded to sacco_loan_guarantees by signing_requests_kind_source_chk, so
    // this flag hides a kind that is unusable for a company tenant rather than
    // being the thing that keeps them out. The database is the gate.
    saccoOnly: true,
  },
  contract: {
    label: 'Contracts & agreements',
    sourceTable: 'generated_contracts',
    blurb: 'Hire purchase, sale and service agreements generated by the system.',
  },
};

export const docKindLabel = (k) => DOC_KINDS[k]?.label || 'Document';

/** Kinds a tenant with no sacco can never use. */
export const isSaccoOnlyKind = (k) => !!DOC_KINDS[k]?.saccoOnly;

/**
 * The role a guarantee agreement's own guarantor signs under.
 *
 * Named once because three things have to agree about it: the panel the send
 * screen pins, the caption printed under the signature line, and the role SignNow
 * ties the signing box to. A typo in any one of them puts the guarantor's box
 * over the society's line.
 */
export const GUARANTOR_ROLE = 'Guarantor';

/**
 * The panel a document kind is signed by, when the tenant has not named one.
 *
 * These mirror the signature blocks the existing certificates already print —
 * the share certificate has drawn Chairperson / Treasurer / Secretary lines
 * since it was written — so turning signing on does not change what the paper
 * claims, only whether the claim is backed.
 */
export const DEFAULT_PANELS = {
  share_certificate: [
    { role: 'Chairperson', order: 1 },
    { role: 'Treasurer', order: 2 },
    { role: 'Secretary', order: 3 },
  ],
  settlement_certificate: [
    { role: 'Authorised Officer', order: 1 },
    { role: 'Director', order: 2 },
  ],
  asset_valuation: [
    { role: 'Valuer', order: 1 },
    { role: 'Treasurer', order: 2 },
  ],
  // The guarantor signs their own undertaking; the society countersigns it as
  // the party taking the benefit of it. A guarantee signed only by the society
  // is not a guarantee, and one signed only by the guarantor is not accepted —
  // so both are the default, and the guarantor goes first.
  guarantee_agreement: [
    { role: GUARANTOR_ROLE, order: 1 },
    { role: 'Authorised Officer', order: 2 },
  ],
  contract: [
    { role: 'Authorised Officer', order: 1 },
  ],
};

export const defaultPanelFor = (kind) =>
  (DEFAULT_PANELS[kind] || DEFAULT_PANELS.contract).map((p) => ({ ...p, name: '', email: '' }));

// ── Page geometry ───────────────────────────────────────────────────────────
export const A4 = {
  portrait: { width: 595.28, height: 841.89 },
  landscape: { width: 841.89, height: 595.28 },
};

/** How tall a signature block is, and how much room its ruled line needs. */
export const SIG_BLOCK = { width: 150, height: 40, dateHeight: 14, gap: 28 };

/** Side margin the signature row is laid out within. */
const SIG_MARGIN = 40;

/**
 * Lay `count` signature blocks across the foot of a page.
 *
 * Returns the top-left corner of each signing box plus the y of the ruled line
 * that goes under it, so the generator can draw the line and the caption while
 * the signing box sits directly above — which is what a wet-ink signature does
 * on paper, and what a reader expects to see.
 *
 * `bottomOffset` is measured from the bottom of the page, because that is how
 * every certificate design in this codebase positions its signature row: a
 * fixed distance up from the foot, whatever is above it.
 *
 * A row that does not fit at the preferred width SHRINKS — both the gap and the
 * blocks themselves. Keeping the block width fixed and only tightening the gap
 * looks like it works for three officers and silently pushes the fourth off the
 * edge of the page, where SignNow would place a signing box nobody can reach.
 */
export const signatureBlocks = (count, { width, height }, bottomOffset = 120) => {
  const n = Math.max(1, count);
  const available = Math.max(1, width - SIG_MARGIN * 2);

  let gap = n > 1 ? SIG_BLOCK.gap : 0;
  let w = SIG_BLOCK.width;

  if (n * w + (n - 1) * gap > available) {
    // Give up the gap first — the space between blocks is decoration, the
    // block itself is the thing a signature has to land inside.
    gap = n > 1 ? Math.min(gap, available * 0.04) : 0;
    w = (available - (n - 1) * gap) / n;
  }

  const total = n * w + (n - 1) * gap;
  const startX = SIG_MARGIN + (available - total) / 2;
  const boxTop = height - bottomOffset - SIG_BLOCK.height;

  return Array.from({ length: n }, (_, i) => ({
    index: i,
    x: startX + i * (w + gap),
    y: boxTop,
    width: w,
    height: SIG_BLOCK.height,
    /** The ruled line the signature sits on. */
    lineY: boxTop + SIG_BLOCK.height + 2,
    /** Where the office caption goes, under the line. */
    captionY: boxTop + SIG_BLOCK.height + 14,
  }));
};

/**
 * The field list sent to signnow-documents, built from the same blocks the
 * generator drew. `role` is what ties a field to a signer row, so it must be
 * the signer's role_name exactly.
 */
export const fieldsForSigners = (signers, page, geometry, bottomOffset) => {
  const blocks = signatureBlocks(signers.length, geometry, bottomOffset);
  return signers.map((s, i) => ({
    role: s.role,
    page,
    x: blocks[i].x,
    y: blocks[i].y,
    width: blocks[i].width,
    height: blocks[i].height,
    withDate: true,
  }));
};

// ── Status vocabulary ───────────────────────────────────────────────────────

/**
 * One line about where a signing request has got to, and the tone to say it in.
 *
 * `released` is the only state in which the document is the issued certificate.
 * Everything else — including `signed` — is deliberately NOT presented as
 * issued, because a tenant that turned auto-release off has chosen to have a
 * person look at it first.
 */
export const SIGNING_VERDICTS = {
  draft: { tone: 'muted', label: 'Not sent', detail: 'Generated, but nobody has been asked to sign it yet.' },
  sent: { tone: 'pending', label: 'Out for signature', detail: 'Waiting on the signatories.' },
  viewed: { tone: 'pending', label: 'Opened', detail: 'A signatory has opened it but not signed.' },
  signed: { tone: 'success', label: 'Signed', detail: 'Every signatory has signed. Awaiting release.' },
  released: { tone: 'success', label: 'Issued', detail: 'Signed by every signatory and issued as the certificate of record.' },
  declined: { tone: 'danger', label: 'Declined', detail: 'A signatory refused to sign.' },
  cancelled: { tone: 'muted', label: 'Withdrawn', detail: 'The request was withdrawn before it was signed.' },
  expired: { tone: 'warning', label: 'Expired', detail: 'The invite lapsed before everyone signed.' },
  failed: { tone: 'danger', label: 'Failed to send', detail: 'The document never reached SignNow.' },
};

/**
 * Where the certificate vocabulary is simply the wrong word.
 *
 * A guarantee agreement is not "issued" — nobody issues an undertaking to
 * themselves. It is EXECUTED, and the distinction is the whole point of routing
 * it through SignNow: an issued certificate is a claim the society makes, an
 * executed agreement is one the guarantor made. Only the states where the two
 * vocabularies actually differ are overridden.
 */
const KIND_VERDICTS = {
  guarantee_agreement: {
    signed: {
      tone: 'success',
      label: 'Signed',
      detail: 'Every party has signed. Awaiting release as the executed agreement.',
    },
    released: {
      tone: 'success',
      label: 'Executed',
      detail: 'Signed by every party and stored as the executed agreement of record.',
    },
    failed: { tone: 'danger', label: 'Failed to send', detail: 'The agreement never reached SignNow.' },
  },
};

export const signingVerdict = (status, docKind) =>
  KIND_VERDICTS[docKind]?.[status]
  || SIGNING_VERDICTS[status]
  || { tone: 'muted', label: 'Unknown', detail: '' };

/** Terminal states: nothing more will happen without somebody starting again. */
export const isTerminal = (status) =>
  ['released', 'declined', 'cancelled', 'expired', 'failed'].includes(status);

/** Is this document releasable as the certificate of record? */
export const isIssued = (status) => status === 'released';

/**
 * Whether a certificate may be handed out.
 *
 * Three-way on purpose, because "no" has two very different reasons and the
 * screen has to say which:
 *   allowed  — hand it over
 *   draft    — signing is not required here, so an unsigned copy is the norm
 *   blocked  — signing IS required and has not completed
 */
export const releaseState = (requireSignature, request) => {
  if (isIssued(request?.status)) return { kind: 'allowed', signed: true };
  if (!requireSignature) return { kind: 'draft', signed: false };
  return {
    kind: 'blocked',
    signed: false,
    reason: request
      ? signingVerdict(request.status).detail
      : 'This certificate has to be signed before it can be issued.',
  };
};

/** A signer entry the RPC will accept, or null when it is not usable. */
export const cleanSigner = (s, index) => {
  const email = String(s?.email || '').trim().toLowerCase();
  const role = String(s?.role || '').trim();
  if (!email || !role) return null;
  if (!/^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(email)) return null;
  return {
    role,
    name: String(s?.name || '').trim() || null,
    email,
    order: Number(s?.order) || index + 1,
  };
};

export const cleanPanel = (list) =>
  (Array.isArray(list) ? list : []).map(cleanSigner).filter(Boolean);
