-- ═══════════════════════════════════════════════════════════════════════════
-- HR DEMO DATA — employees + payroll for one tenant
--
-- Generated by scripts/seed-hr-demo.mjs. Do not edit by hand — regenerate.
-- Undo with scripts/seed-hr-demo-teardown.sql.
--
-- Tenant: the admin account sbcdevwork5812@gmail.com. Aborts if that is not an admin.
-- 10 employees (demo.hr.*@example.com, cannot sign in) and
-- 30 payroll records for 2026-07, 2026-08, 2026-09. The tenant's own
-- employees and ledger are not touched.
--
-- Expected totals for these employees alone, per month:
--   2026-07: 10 staff  gross 1,199,000  PAYE 243,516  NSSF 39,240  SHIF 32,972.5  AHL 17,985  net 821,286.5
--   2026-08: 10 staff  gross 1,219,550  PAYE 249,419  NSSF 39,240  SHIF 33,537.63  AHL 18,293.25  net 835,060.12
--   2026-09: 10 staff  gross 1,199,000  PAYE 243,516  NSSF 39,240  SHIF 32,972.5  AHL 17,985  net 821,286.5
--
-- Idempotent: re-running changes nothing.
-- ═══════════════════════════════════════════════════════════════════════════
begin;

create temp table _hr_demo_ctx on commit drop as
  select up.id as admin_id from public.user_profiles up
   where lower(up.email) = lower('sbcdevwork5812@gmail.com') and up.role = 'admin';
do $$
begin
  if (select count(*) from _hr_demo_ctx) <> 1 then
    raise exception 'HR demo seed: expected exactly one admin account for sbcdevwork5812@gmail.com';
  end if;
end $$;

-- user_profiles.id references auth.users, so each employee needs an auth row.
-- No identity row and an unusable password: these are payroll records, not
-- logins — the same stance the HR page takes when it adds an employee.
insert into auth.users (
  instance_id, id, aud, role, email, encrypted_password,
  email_confirmed_at, created_at, updated_at, raw_app_meta_data, raw_user_meta_data)
select
  '00000000-0000-0000-0000-000000000000'::uuid, v.id::uuid, 'authenticated', 'authenticated',
  v.email, '', now(), now(), now(),
  '{"provider":"email","providers":["email"]}'::jsonb,
  jsonb_build_object('full_name', v.full_name)
from (values
    ('0eb40386-614a-51b0-bc9f-ee4c33e4a8ca', 'demo.hr.wanjiku@example.com', 'Wanjiku Kariuki'),
    ('ad087e12-9229-59e2-a2f8-731a4547b452', 'demo.hr.odhiambo@example.com', 'Kevin Odhiambo'),
    ('fd847e75-aa9c-5624-bf11-0612c55174fd', 'demo.hr.achieng@example.com', 'Faith Achieng'),
    ('7ef4f002-78f2-5eb8-b611-a9d3dbc9da12', 'demo.hr.mwangi@example.com', 'Daniel Mwangi'),
    ('1a8600a0-e244-5b51-a3a0-5a36d7434751', 'demo.hr.njeri@example.com', 'Ruth Njeri'),
    ('f5304493-a6f1-5097-b2ae-1b384c8722f5', 'demo.hr.kiprono@example.com', 'Brian Kiprono'),
    ('8f6ce8a5-6f52-5d04-96d0-b0705479bd99', 'demo.hr.atieno@example.com', 'Mary Atieno'),
    ('898fad46-18d8-579a-b596-0bdfdadc61e5', 'demo.hr.omondi@example.com', 'Collins Omondi'),
    ('2887168c-09a9-5d54-907d-9c9c37e5e9d3', 'demo.hr.wambui@example.com', 'Grace Wambui'),
    ('5192b3d0-66f7-53c3-ad9b-bf76977670bb', 'demo.hr.mutua@example.com', 'James Mutua')
) as v(id, email, full_name)
on conflict do nothing;

-- GoTrue reads these token columns as NOT NULL text; square away any nulls.
do $$
declare col text;
begin
  foreach col in array array[
    'confirmation_token','recovery_token','email_change_token_new','email_change',
    'email_change_token_current','phone_change','phone_change_token','reauthentication_token']
  loop
    if exists (select 1 from information_schema.columns
                where table_schema = 'auth' and table_name = 'users' and column_name = col) then
      execute format('update auth.users set %I = coalesce(%I, %L) where id = any($1)', col, col, '')
        using array['0eb40386-614a-51b0-bc9f-ee4c33e4a8ca', 'ad087e12-9229-59e2-a2f8-731a4547b452', 'fd847e75-aa9c-5624-bf11-0612c55174fd', '7ef4f002-78f2-5eb8-b611-a9d3dbc9da12', '1a8600a0-e244-5b51-a3a0-5a36d7434751', 'f5304493-a6f1-5097-b2ae-1b384c8722f5', '8f6ce8a5-6f52-5d04-96d0-b0705479bd99', '898fad46-18d8-579a-b596-0bdfdadc61e5', '2887168c-09a9-5d54-907d-9c9c37e5e9d3', '5192b3d0-66f7-53c3-ad9b-bf76977670bb']::uuid[];
    end if;
  end loop;
end $$;

-- handle_new_user normally writes the bare profile; do it explicitly too so
-- the seed does not depend on that trigger.
insert into public.user_profiles (id, email, full_name, role)
select v.id::uuid, v.email, v.full_name, 'staff'::public.user_role
from (values
    ('0eb40386-614a-51b0-bc9f-ee4c33e4a8ca', 'demo.hr.wanjiku@example.com', 'Wanjiku Kariuki'),
    ('ad087e12-9229-59e2-a2f8-731a4547b452', 'demo.hr.odhiambo@example.com', 'Kevin Odhiambo'),
    ('fd847e75-aa9c-5624-bf11-0612c55174fd', 'demo.hr.achieng@example.com', 'Faith Achieng'),
    ('7ef4f002-78f2-5eb8-b611-a9d3dbc9da12', 'demo.hr.mwangi@example.com', 'Daniel Mwangi'),
    ('1a8600a0-e244-5b51-a3a0-5a36d7434751', 'demo.hr.njeri@example.com', 'Ruth Njeri'),
    ('f5304493-a6f1-5097-b2ae-1b384c8722f5', 'demo.hr.kiprono@example.com', 'Brian Kiprono'),
    ('8f6ce8a5-6f52-5d04-96d0-b0705479bd99', 'demo.hr.atieno@example.com', 'Mary Atieno'),
    ('898fad46-18d8-579a-b596-0bdfdadc61e5', 'demo.hr.omondi@example.com', 'Collins Omondi'),
    ('2887168c-09a9-5d54-907d-9c9c37e5e9d3', 'demo.hr.wambui@example.com', 'Grace Wambui'),
    ('5192b3d0-66f7-53c3-ad9b-bf76977670bb', 'demo.hr.mutua@example.com', 'James Mutua')
) as v(id, email, full_name)
on conflict (id) do nothing;

-- Tenant, role and the pay the payroll engine reads. admin_id and role are
-- trigger-guarded, which lets this through because the SQL editor has no JWT.
update public.user_profiles p set
  admin_id = c.admin_id, full_name = v.full_name, role = v.role::public.user_role,
  department = v.dept, phone = v.phone, gender = v.gender, date_of_birth = v.dob::date,
  is_active = true, employment_type = v.emp_type, date_joined = v.joined::date,
  basic_salary = v.basic, housing_allowance = v.house, transport_allowance = v.transport,
  pension_contribution = v.pension, insurance_premiums = v.insurance,
  national_id = v.nid, kra_pin = v.pin, sha_number = v.sha
from _hr_demo_ctx c, (values
    ('0eb40386-614a-51b0-bc9f-ee4c33e4a8ca', 'Wanjiku Kariuki', 'manager', 'Management', '+254710000010', 'female', '1982-02-11', 'full_time', '2021-01-04', 250000, 40000, 20000, 15000, 5000, '30000000', 'A090000000A', 'SHA700000000'),
    ('ad087e12-9229-59e2-a2f8-731a4547b452', 'Kevin Odhiambo', 'finance', 'Finance', '+254710000011', 'male', '1987-07-23', 'full_time', '2021-06-14', 165000, 25000, 15000, 10000, 3000, '31111111', 'A091234567B', 'SHA700003571'),
    ('fd847e75-aa9c-5624-bf11-0612c55174fd', 'Faith Achieng', 'accountant', 'Finance', '+254710000012', 'female', '1992-10-05', 'full_time', '2022-03-01', 98000, 15000, 10000, 5000, 0, '32222222', 'A092469134C', 'SHA700007142'),
    ('7ef4f002-78f2-5eb8-b611-a9d3dbc9da12', 'Daniel Mwangi', 'sales_agent', 'Sales', '+254710000013', 'male', '1990-04-18', 'full_time', '2022-08-15', 72000, 10000, 12000, 0, 0, '33333333', 'A093703701D', 'SHA700010713'),
    ('1a8600a0-e244-5b51-a3a0-5a36d7434751', 'Ruth Njeri', 'sales_agent', 'Sales', '+254710000014', 'female', '1994-12-02', 'full_time', '2023-02-06', 65000, 10000, 12000, 0, 0, '34444444', 'A094938268E', 'SHA700014284'),
    ('f5304493-a6f1-5097-b2ae-1b384c8722f5', 'Brian Kiprono', 'operations', 'Operations', '+254710000015', 'male', '1991-08-29', 'full_time', '2022-11-21', 58000, 8000, 8000, 0, 2000, '35555555', 'A096172835F', 'SHA700017855'),
    ('8f6ce8a5-6f52-5d04-96d0-b0705479bd99', 'Mary Atieno', 'staff', 'HR', '+254710000016', 'female', '1989-03-14', 'full_time', '2021-09-01', 75000, 10000, 8000, 3000, 0, '36666666', 'A097407402G', 'SHA700021426'),
    ('898fad46-18d8-579a-b596-0bdfdadc61e5', 'Collins Omondi', 'staff', 'IT', '+254710000017', 'male', '1993-05-09', 'full_time', '2023-05-02', 110000, 15000, 10000, 6000, 2500, '37777777', 'A098641969H', 'SHA700024997'),
    ('2887168c-09a9-5d54-907d-9c9c37e5e9d3', 'Grace Wambui', 'staff', 'Administration', '+254710000018', 'female', '1996-01-27', 'full_time', '2024-01-08', 42000, 5000, 5000, 0, 0, '38888888', 'A099876536J', 'SHA700028568'),
    ('5192b3d0-66f7-53c3-ad9b-bf76977670bb', 'James Mutua', 'staff', 'Operations', '+254710000019', 'male', '1998-06-30', 'contract', '2025-02-03', 22000, 2000, 2000, 0, 0, '39999999', 'A010111110K', 'SHA700032139')
) as v(id, full_name, role, dept, phone, gender, dob, emp_type, joined, basic, house, transport, pension, insurance, nid, pin, sha)
where p.id = v.id::uuid;

insert into public.payroll_records (admin_id, id, employee_id, pay_month, basic_salary, housing_allowance, transport_allowance, meal_allowance, bonus, gift, loan_deduction, advance_deduction, gross_salary, taxable_pay, paye, nssf, shif, housing_levy, personal_relief, insurance_relief, pension_contribution, non_cash_benefits, total_deductions, net_salary, rate_version, status)
select c.admin_id, v.id::uuid, v.employee_id::uuid, v.pay_month, v.basic_salary, v.housing_allowance, v.transport_allowance, v.meal_allowance, v.bonus, v.gift, v.loan_deduction, v.advance_deduction, v.gross_salary, v.taxable_pay, v.paye, v.nssf, v.shif, v.housing_levy, v.personal_relief, v.insurance_relief, v.pension_contribution, v.non_cash_benefits, v.total_deductions, v.net_salary, v.rate_version, v.status
from _hr_demo_ctx c, (values
    ('3c8151fc-29e7-54d4-9808-61c8da942a0e', '0eb40386-614a-51b0-bc9f-ee4c33e4a8ca', '2026-07', 250000, 40000, 20000, 0, 0, 0, 0, 0, 310000, 277505, 74885, 4320, 8525, 4650, 2400, 750, 15000, 0, 107380, 202620, '2025-02-01', 'paid'),
    ('2b18e4dd-d0ae-5189-976d-75cc91983509', 'ad087e12-9229-59e2-a2f8-731a4547b452', '2026-07', 165000, 25000, 15000, 0, 0, 0, 0, 0, 205000, 181967.5, 46524, 4320, 5637.5, 3075, 2400, 450, 10000, 0, 69556.5, 135443.5, '2025-02-01', 'paid'),
    ('9b499a9e-65ac-5cde-9cb6-d2357f3d9ee4', 'fd847e75-aa9c-5624-bf11-0612c55174fd', '2026-07', 98000, 15000, 10000, 0, 0, 0, 0, 0, 123000, 108452.5, 24919, 4320, 3382.5, 1845, 2400, 0, 5000, 0, 39466.5, 83533.5, '2025-02-01', 'paid'),
    ('3abf6ab5-e778-5982-8245-efd69cd818d6', '7ef4f002-78f2-5eb8-b611-a9d3dbc9da12', '2026-07', 72000, 10000, 12000, 0, 0, 0, 0, 0, 94000, 85685, 18089, 4320, 2585, 1410, 2400, 0, 0, 0, 26404, 67596, '2025-02-01', 'paid'),
    ('2d81cf4a-f952-5ac3-834e-f57412303d72', '1a8600a0-e244-5b51-a3a0-5a36d7434751', '2026-07', 65000, 10000, 12000, 0, 0, 0, 0, 0, 87000, 78982.5, 16078, 4320, 2392.5, 1305, 2400, 0, 0, 0, 24095.5, 62904.5, '2025-02-01', 'paid'),
    ('10e265b8-e311-59fa-a44b-e09e677ab78e', 'f5304493-a6f1-5097-b2ae-1b384c8722f5', '2026-07', 58000, 8000, 8000, 0, 0, 0, 5000, 0, 74000, 66535, 12044, 4320, 2035, 1110, 2400, 300, 0, 0, 24509, 49491, '2025-02-01', 'paid'),
    ('eb9c3bea-bc10-5880-82cd-911f0ce19a34', '8f6ce8a5-6f52-5d04-96d0-b0705479bd99', '2026-07', 75000, 10000, 8000, 0, 0, 0, 0, 0, 93000, 81727.5, 16902, 4320, 2557.5, 1395, 2400, 0, 3000, 0, 28174.5, 64825.5, '2025-02-01', 'paid'),
    ('bdd30a8a-3e8b-5e10-86b9-5acb0447a041', '898fad46-18d8-579a-b596-0bdfdadc61e5', '2026-07', 110000, 15000, 10000, 0, 0, 0, 0, 0, 135000, 118942.5, 27691, 4320, 3712.5, 2025, 2400, 375, 6000, 0, 43748.5, 91251.5, '2025-02-01', 'paid'),
    ('ddafb040-922f-5e0d-afdf-f0f50ff511bf', '2887168c-09a9-5d54-907d-9c9c37e5e9d3', '2026-07', 42000, 5000, 5000, 0, 0, 0, 0, 0, 52000, 46670, 6384, 3120, 1430, 780, 2400, 0, 0, 0, 11714, 40286, '2025-02-01', 'paid'),
    ('2afd8a86-5374-586a-89fe-1a6e0358e4df', '5192b3d0-66f7-53c3-ad9b-bf76977670bb', '2026-07', 22000, 2000, 2000, 0, 0, 0, 0, 0, 26000, 23335, 0, 1560, 715, 390, 2400, 0, 0, 0, 2665, 23335, '2025-02-01', 'paid'),
    ('89d12759-cb94-5c7b-a8c9-6e324f69e46f', '0eb40386-614a-51b0-bc9f-ee4c33e4a8ca', '2026-08', 250000, 40000, 20000, 0, 0, 0, 0, 0, 310000, 277505, 74885, 4320, 8525, 4650, 2400, 750, 15000, 0, 107380, 202620, '2025-02-01', 'paid'),
    ('a8ed1664-aa29-5f55-bb14-78bb26fda7ed', 'ad087e12-9229-59e2-a2f8-731a4547b452', '2026-08', 165000, 25000, 15000, 0, 0, 0, 0, 0, 205000, 181967.5, 46524, 4320, 5637.5, 3075, 2400, 450, 10000, 0, 69556.5, 135443.5, '2025-02-01', 'paid'),
    ('e33821fe-0c2c-5ad4-bd8f-bfbfc3e766ad', 'fd847e75-aa9c-5624-bf11-0612c55174fd', '2026-08', 98000, 15000, 10000, 0, 0, 0, 0, 0, 123000, 108452.5, 24919, 4320, 3382.5, 1845, 2400, 0, 5000, 0, 39466.5, 83533.5, '2025-02-01', 'paid'),
    ('2f8d56a3-0000-563a-a915-479af04e78de', '7ef4f002-78f2-5eb8-b611-a9d3dbc9da12', '2026-08', 72000, 10000, 12000, 0, 10800, 0, 0, 0, 104800, 96026, 21191, 4320, 2882, 1572, 2400, 0, 0, 0, 29965, 74835, '2025-02-01', 'paid'),
    ('87b5e603-f732-59cf-be0f-0b0816228606', '1a8600a0-e244-5b51-a3a0-5a36d7434751', '2026-08', 65000, 10000, 12000, 0, 9750, 0, 0, 0, 96750, 88318.12, 18879, 4320, 2660.63, 1451.25, 2400, 0, 0, 0, 27310.88, 69439.12, '2025-02-01', 'paid'),
    ('888aa8ca-fdba-5e3e-b43e-a7d51d131c7e', 'f5304493-a6f1-5097-b2ae-1b384c8722f5', '2026-08', 58000, 8000, 8000, 0, 0, 0, 5000, 0, 74000, 66535, 12044, 4320, 2035, 1110, 2400, 300, 0, 0, 24509, 49491, '2025-02-01', 'paid'),
    ('f150f98c-b9ef-5f2e-8716-70f3e01911ae', '8f6ce8a5-6f52-5d04-96d0-b0705479bd99', '2026-08', 75000, 10000, 8000, 0, 0, 0, 0, 0, 93000, 81727.5, 16902, 4320, 2557.5, 1395, 2400, 0, 3000, 0, 28174.5, 64825.5, '2025-02-01', 'paid'),
    ('0f15f561-f9ed-5336-918c-fc155cf1f287', '898fad46-18d8-579a-b596-0bdfdadc61e5', '2026-08', 110000, 15000, 10000, 0, 0, 0, 0, 0, 135000, 118942.5, 27691, 4320, 3712.5, 2025, 2400, 375, 6000, 0, 43748.5, 91251.5, '2025-02-01', 'paid'),
    ('2dba9ec4-6a0e-5956-8c8f-810c8c38a55e', '2887168c-09a9-5d54-907d-9c9c37e5e9d3', '2026-08', 42000, 5000, 5000, 0, 0, 0, 0, 0, 52000, 46670, 6384, 3120, 1430, 780, 2400, 0, 0, 0, 11714, 40286, '2025-02-01', 'paid'),
    ('130b1ff3-b0bc-53e7-8d6a-b7688c92a4e2', '5192b3d0-66f7-53c3-ad9b-bf76977670bb', '2026-08', 22000, 2000, 2000, 0, 0, 0, 0, 0, 26000, 23335, 0, 1560, 715, 390, 2400, 0, 0, 0, 2665, 23335, '2025-02-01', 'paid'),
    ('617d6b7c-cc43-543d-bc41-9a4a6ecae613', '0eb40386-614a-51b0-bc9f-ee4c33e4a8ca', '2026-09', 250000, 40000, 20000, 0, 0, 0, 0, 0, 310000, 277505, 74885, 4320, 8525, 4650, 2400, 750, 15000, 0, 107380, 202620, '2025-02-01', 'pending'),
    ('b7cccd30-7a6a-5cf4-9786-373094bc36f8', 'ad087e12-9229-59e2-a2f8-731a4547b452', '2026-09', 165000, 25000, 15000, 0, 0, 0, 0, 0, 205000, 181967.5, 46524, 4320, 5637.5, 3075, 2400, 450, 10000, 0, 69556.5, 135443.5, '2025-02-01', 'pending'),
    ('ed23cfc1-a490-5ebf-9258-03f72ef48ae2', 'fd847e75-aa9c-5624-bf11-0612c55174fd', '2026-09', 98000, 15000, 10000, 0, 0, 0, 0, 0, 123000, 108452.5, 24919, 4320, 3382.5, 1845, 2400, 0, 5000, 0, 39466.5, 83533.5, '2025-02-01', 'pending'),
    ('5986afb8-484c-5f6b-9327-fed13d74f7b4', '7ef4f002-78f2-5eb8-b611-a9d3dbc9da12', '2026-09', 72000, 10000, 12000, 0, 0, 0, 0, 0, 94000, 85685, 18089, 4320, 2585, 1410, 2400, 0, 0, 0, 26404, 67596, '2025-02-01', 'pending'),
    ('9595d0de-1e49-53de-87ec-ff7c90d42b66', '1a8600a0-e244-5b51-a3a0-5a36d7434751', '2026-09', 65000, 10000, 12000, 0, 0, 0, 0, 0, 87000, 78982.5, 16078, 4320, 2392.5, 1305, 2400, 0, 0, 0, 24095.5, 62904.5, '2025-02-01', 'pending'),
    ('4467e6b7-3a49-52cf-a001-dbafbde6b91b', 'f5304493-a6f1-5097-b2ae-1b384c8722f5', '2026-09', 58000, 8000, 8000, 0, 0, 0, 5000, 0, 74000, 66535, 12044, 4320, 2035, 1110, 2400, 300, 0, 0, 24509, 49491, '2025-02-01', 'pending'),
    ('b9c9d044-8c55-5c37-8280-6267c407f2c7', '8f6ce8a5-6f52-5d04-96d0-b0705479bd99', '2026-09', 75000, 10000, 8000, 0, 0, 0, 0, 0, 93000, 81727.5, 16902, 4320, 2557.5, 1395, 2400, 0, 3000, 0, 28174.5, 64825.5, '2025-02-01', 'pending'),
    ('c41addab-bfcf-52a1-9f0a-a9614d885c12', '898fad46-18d8-579a-b596-0bdfdadc61e5', '2026-09', 110000, 15000, 10000, 0, 0, 0, 0, 0, 135000, 118942.5, 27691, 4320, 3712.5, 2025, 2400, 375, 6000, 0, 43748.5, 91251.5, '2025-02-01', 'pending'),
    ('34be1e52-89b4-59c9-8b53-60214bdaf972', '2887168c-09a9-5d54-907d-9c9c37e5e9d3', '2026-09', 42000, 5000, 5000, 0, 0, 0, 0, 0, 52000, 46670, 6384, 3120, 1430, 780, 2400, 0, 0, 0, 11714, 40286, '2025-02-01', 'pending'),
    ('31d86863-ccd0-533a-bf7c-8a00a6d65965', '5192b3d0-66f7-53c3-ad9b-bf76977670bb', '2026-09', 22000, 2000, 2000, 0, 0, 0, 0, 0, 26000, 23335, 0, 1560, 715, 390, 2400, 0, 0, 0, 2665, 23335, '2025-02-01', 'pending')
) as v(id, employee_id, pay_month, basic_salary, housing_allowance, transport_allowance, meal_allowance, bonus, gift, loan_deduction, advance_deduction, gross_salary, taxable_pay, paye, nssf, shif, housing_levy, personal_relief, insurance_relief, pension_contribution, non_cash_benefits, total_deductions, net_salary, rate_version, status)
on conflict do nothing;

-- What went in, for the log.
select 'employees' as what, count(*) as n from public.user_profiles where id = any(array['0eb40386-614a-51b0-bc9f-ee4c33e4a8ca', 'ad087e12-9229-59e2-a2f8-731a4547b452', 'fd847e75-aa9c-5624-bf11-0612c55174fd', '7ef4f002-78f2-5eb8-b611-a9d3dbc9da12', '1a8600a0-e244-5b51-a3a0-5a36d7434751', 'f5304493-a6f1-5097-b2ae-1b384c8722f5', '8f6ce8a5-6f52-5d04-96d0-b0705479bd99', '898fad46-18d8-579a-b596-0bdfdadc61e5', '2887168c-09a9-5d54-907d-9c9c37e5e9d3', '5192b3d0-66f7-53c3-ad9b-bf76977670bb']::uuid[])
union all select 'payroll_records', count(*) from public.payroll_records where id = any(array['3c8151fc-29e7-54d4-9808-61c8da942a0e', '2b18e4dd-d0ae-5189-976d-75cc91983509', '9b499a9e-65ac-5cde-9cb6-d2357f3d9ee4', '3abf6ab5-e778-5982-8245-efd69cd818d6', '2d81cf4a-f952-5ac3-834e-f57412303d72', '10e265b8-e311-59fa-a44b-e09e677ab78e', 'eb9c3bea-bc10-5880-82cd-911f0ce19a34', 'bdd30a8a-3e8b-5e10-86b9-5acb0447a041', 'ddafb040-922f-5e0d-afdf-f0f50ff511bf', '2afd8a86-5374-586a-89fe-1a6e0358e4df', '89d12759-cb94-5c7b-a8c9-6e324f69e46f', 'a8ed1664-aa29-5f55-bb14-78bb26fda7ed', 'e33821fe-0c2c-5ad4-bd8f-bfbfc3e766ad', '2f8d56a3-0000-563a-a915-479af04e78de', '87b5e603-f732-59cf-be0f-0b0816228606', '888aa8ca-fdba-5e3e-b43e-a7d51d131c7e', 'f150f98c-b9ef-5f2e-8716-70f3e01911ae', '0f15f561-f9ed-5336-918c-fc155cf1f287', '2dba9ec4-6a0e-5956-8c8f-810c8c38a55e', '130b1ff3-b0bc-53e7-8d6a-b7688c92a4e2', '617d6b7c-cc43-543d-bc41-9a4a6ecae613', 'b7cccd30-7a6a-5cf4-9786-373094bc36f8', 'ed23cfc1-a490-5ebf-9258-03f72ef48ae2', '5986afb8-484c-5f6b-9327-fed13d74f7b4', '9595d0de-1e49-53de-87ec-ff7c90d42b66', '4467e6b7-3a49-52cf-a001-dbafbde6b91b', 'b9c9d044-8c55-5c37-8280-6267c407f2c7', 'c41addab-bfcf-52a1-9f0a-a9614d885c12', '34be1e52-89b4-59c9-8b53-60214bdaf972', '31d86863-ccd0-533a-bf7c-8a00a6d65965']::uuid[]);

commit;
